
post http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

###


post http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc4Mjc3MzkyfQ.CTnVhiZ_8PuV-3oGH2GEiIYwRPDkC5RkvH4ovfJzjdw
Content-Type: application/json

{
 "tweet":"hi"
}


###

get http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc4Mjc3MzkyfQ.CTnVhiZ_8PuV-3oGH2GEiIYwRPDkC5RkvH4ovfJzjdw

###

get http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2Mzk4NjkzfQ.rTRdVEtkYvsaTFl1_kQfScy-i7ZWZgjIea8wNbHcTdE

###

delete http://localhost:3000/tweets/17/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc3OTU3MzU3fQ.zYloFWxGiXajZurfpQ5NoD3WIZ4CjI3Xswsrvs8uq2Y

###

get http://localhost:3000/tweets/1/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc4MDM1Njg3fQ.ODZD5YRATRVf_8oKtDzjqcxCmy49lRn8FhjSw_3FRnM

###

get http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc4MTI3MzAxfQ.CysX839BV4BSvky1hIiX3NEiXDiGdwf1OFce-ZYLCGg