
post http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

###

get http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2Mzk4MTQxfQ.PF09CmFgwTkWmEv7rMDWHBstlHbKVjjt7KNdnqSxQ_w

###

get http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc2Mzk4NjkzfQ.rTRdVEtkYvsaTFl1_kQfScy-i7ZWZgjIea8wNbHcTdE

###

get http://localhost:3000/tweets/1/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc3OTU3MzU3fQ.zYloFWxGiXajZurfpQ5NoD3WIZ4CjI3Xswsrvs8uq2Y

###

get http://localhost:3000/tweets/1/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc4MDM1Njg3fQ.ODZD5YRATRVf_8oKtDzjqcxCmy49lRn8FhjSw_3FRnM

###

get http://localhost:3000/user/tweets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjc4MDQyNTEwfQ.GnIK4wg97tjlabYBnGpEVKm0vBu-XEKdjMLyyPWNe9k